name: NectarCam2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - pip
  - scipy
  - scikit-learn
  - ipykernel 
  - pyserial 
  - peakutils
  - scikit-image
  - opencv
 #  - opencv # after installing env, install open cv with conda install -c menpo opencv

  # also need spinnaker-python with python -m pip install spinnaker_python-1.x.x.x-cp36-cp36m-win_amd64.whl
