name: NectarLearning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib=3.0
  - numpy=1.15
  - pandas=0.24
  - pip=19.0 
  - scipy=1.2
  - scikit-learn=0.20
  - ipykernel=5.1 # after install, activate environment and type python -m ipykernel install --user --name NectarLearning
  - pyserial=3.7 # for connecting with arduino